# Advanced Packaging Tool
- src: https://github.com/vterdunov/ansible-apt
  name: apt

# Ruby Brightbox
- src: https://github.com/vterdunov/ansible-ruby-brightbox
  name: ruby-brightbox

# Network Time Protocol
- src: https://github.com/geerlingguy/ansible-role-ntp
  name: ntp

# ansistrano-deploy
- src: https://github.com/ansistrano/deploy.git
  name: ansistrano-deploy
  version: 1.11.0

# ansistrano-rollback
- src: https://github.com/ansistrano/rollback
  name: ansistrano-rollback

# NodeJS
- src: https://github.com/feksai/ansible-role-nodejs
  name: nodejs

# MySQL
- src: https://github.com/ANXS/mysql
  name: mysql
