# Окружение для разработки
---
- hosts: local
  become: yes

  pre_tasks:
    - name: "Set env variables"
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^export {{ item.var }}="
        line: "export {{ item.var }}={{ item.value }}"
      with_items:
        - { var: "RAILS_ENV", value: "development" }

    - name: "Autofollow to project on logon"
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^cd /vagrant"
        line: "cd /vagrant"

  roles:
    - role: ruby-brightbox
    - role: apt
    - role: ntp
    - role: nodejs
    - role: mysql
