export const CLEAR_RUBRICS = 'RUBRICS/CLEAR';
export const CREATE_RUBRIC = 'RUBRICS/CREATE';
export const DESTROY_RUBRIC = 'RUBRICS/DESTROY';
export const INDEX_RUBRICS = 'RUBRICS/INDEX';
export const SET_ACTIVE_RUBRIC = 'RUBRICS/SET_ACTIVE';
export const UPDATE_RUBRIC = 'RUBRICS/UPDATE';

export const CLEAR_ISSUES = 'ISSUES/CLEAR';
export const CREATE_ISSUE = 'ISSUES/CREATE';
export const DESTROY_ISSUE = 'ISSUES/DESTROY';
export const INDEX_ISSUES = 'ISSUES/INDEX';
export const SET_ACTIVE_ISSUE = 'ISSUES/SET_ACTIVE';
export const UPDATE_ISSUE = 'ISSUES/UPDATE';

export const CREATE_PAPER = 'PAPERS/CREATE';
export const DESTROY_PAPER = 'PAPERS/DESTROY';
export const INDEX_PAPERS = 'PAPERS/INDEX';
export const UPDATE_PAPER = 'PAPERS/UPDATE';
